backend:
  name: git-gateway
  branch: master
media_folder: "public/assets/img"
public_folder: "/assets/img"
collections:
  - name: "blog"
    label: "Articles"
    folder: "src/blog"
    create: true
    slug: "{{day}}-{{month}}-{{year}}-{{slug}}"
    fields:
      - { label: "Titre", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Auteur", name: "author", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Tags", name: "tags", widget: "list", default: ["blog"] }
      - { label: "Ajouter une Image", name: "image", widget: "image" }
      - { label: "Description de l'image", name: "imageAlt", widget: "string" }
      - { label: "Contenu", name: "body", widget: "markdown" }
